---
abstract: 'Debug panel to inspect the Catalyst Stash'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.59
  FindBin: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::Debug::CatalystStash
name: Plack-Middleware-Debug-CatalystStash
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.90050
  Class::Method::Modifiers: 0
  Data::Dumper: 0
  HTML::Entities: 0
  Plack::Middleware::Debug: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/n0body-/plack-middleware-debug-catalyststash/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/n0body-/plack-middleware-debug-catalyststash.git
version: 0.001
